version: "3.7"

# To build changes
# docker-compose -p d6 -f docker-compose.yml -f d6.override.yml -f src.override.yml build
# docker image prune
#   (the build process will create 10GB in iterim images... run this command to clean up iterim images)
# docker-compose -p d6 -f docker-compose.yml -f d6.override.yml -f src.override.yml up -d

services:
  dspace:

    environment:
      - DSPACE_SRC=./dspace/DSpace
    build:
      context: "./dspace/DSpace"
      dockerfile: Dockerfile.jdk8
    image: "elsajin/imagine-rio-dspace:1.0"
